[General]
allow-object-stealing-on-deletion = true
network = src.dtnsim
repeat = 10
sim-time-limit = 604801s
outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"
outputscalarmanager-class="omnetpp::envir::SqliteOutputScalarManager"
**.vector-recording=false
result-dir = results
dtnsim.nodesNumber = 13
dtnsim.node[*].dtn.routing = "cgrModelRev17Distribution"
dtnsim.node[*].dtn.numHags = 5
dtnsim.node[*].dtn.MeanTTF = "2.76_2.9_3.05_3.2_3.34"
dtnsim.node[*].dtn.MeanTTR = "25_25_25_25_25"
dtnsim.node[*].dtn.routingType = "routeListType:allPaths-firstDepleted,volumeAware:allContacts,extensionBlock:on,contactPlan:local,distribution:opportunistic,sdrModel:perNode"
#dtnsim.node[*].dtn.printRoutingDebug=true

dtnsim.central.contactsFile = "../FilteredContactPlans/test.txt"
dtnsim.node[13].app.enable=true
dtnsim.node[13].app.bundlesNumber="20"
dtnsim.node[13].app.start="0"
dtnsim.node[13].app.destinationEid="1"
dtnsim.node[13].app.size="100"


# Nodes's failure rates
dtnsim.node[2].fault.faultSeed = ${repetition}*100
dtnsim.node[2].fault.meanTTF = 2.76h
dtnsim.node[2].fault.meanTTR = 25h
dtnsim.node[4].fault.faultSeed = ${repetition}*100
dtnsim.node[4].fault.meanTTF = 2.9h
dtnsim.node[4].fault.meanTTR = 25h
dtnsim.node[6].fault.faultSeed = ${repetition}*100
dtnsim.node[6].fault.meanTTF = 3.05h
dtnsim.node[6].fault.meanTTR = 25h
dtnsim.node[8].fault.faultSeed = ${repetition}*100
dtnsim.node[8].fault.meanTTF = 3.2h
dtnsim.node[8].fault.meanTTR = 25h
dtnsim.node[10].fault.faultSeed = ${repetition}*100
dtnsim.node[10].fault.meanTTF = 3.34h
dtnsim.node[10].fault.meanTTR = 25h


dtnsim.node[2].fault.enable = true
dtnsim.node[4].fault.enable = true
dtnsim.node[6].fault.enable = true
dtnsim.node[8].fault.enable = true
dtnsim.node[10].fault.enable = true