[General]
allow-object-stealing-on-deletion = true
network = src.dtnsim
repeat = 1
rng-class = "cMersenneTwister"
seed-set = 1000
sim-time-limit = 86400s
outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"
outputscalarmanager-class="omnetpp::envir::SqliteOutputScalarManager"
**.vector-recording=false
result-dir = results
dtnsim.nodesNumber = 109
dtnsim.node[*].dtn.routing = "cgrModelRev17Distribution"
dtnsim.node[*].dtn.numHags = 2
dtnsim.node[*].dtn.MeanTTF = "0.1_2"
dtnsim.node[*].dtn.MeanTTR = "4_4" 
dtnsim.node[*].dtn.routingType = "routeListType:allPaths-firstDepleted,volumeAware:allContacts,extensionBlock:on,contactPlan:global,distribution:equal,sdrModel:perNode"
#dtnsim.node[*].dtn.printRoutingDebug=true

dtnsim.central.contactsFile = "../FilteredContactPlans/contact_plan_7d_node-ids_1LEO-2GS.txt"
#dtnsim.node[*].dtn.saveBundleMap = true
#dtnsim.central.saveTopology = true
#dtnsim.central.saveFlows = true
#dtnsim.central.saveLpFlows = true
dtnsim.node[44].dtn.numberBundles = 100

# traffic generation
dtnsim.node[44].app.enable=true
dtnsim.node[44].app.bundlesNumber="100"
dtnsim.node[44].app.start="0"
dtnsim.node[44].app.destinationEid="1"
dtnsim.node[44].app.size="100"

# Nodes's failure rates
dtnsim.node[2].fault.meanTTR = 4h
dtnsim.node[2].fault.meanTTF = 0.1h
dtnsim.node[4].fault.meanTTR = 4h 
dtnsim.node[4].fault.meanTTF = 2h

dtnsim.node[2].fault.enable = true
dtnsim.node[4].fault.enable = true