[General]
allow-object-stealing-on-deletion = true
network = src.dtnsim
repeat = 20
sim-time-limit = 604801s
outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"
outputscalarmanager-class="omnetpp::envir::SqliteOutputScalarManager"
**.vector-recording=false
result-dir = results
dtnsim.nodesNumber = 109
dtnsim.node[*].dtn.routing = "cgrModel350"
#dtnsim.node[*].dtn.routing = "cgrModelRev17"
dtnsim.node[*].dtn.routingType = "routeListType:allPaths-firstDepleted,volumeAware:allContacts,extensionBlock:on,contactPlan:local"
#dtnsim.node[*].dtn.printRoutingDebug=true

dtnsim.central.contactsFile = "../FilteredContactPlans/contact_plan_7d_node-ids_33LEO_1HAP_1GS.txt"
#dtnsim.node[*].dtn.saveBundleMap = true
#dtnsim.central.saveTopology = true
#dtnsim.central.saveFlows = true
#dtnsim.central.saveLpFlows = true

# traffic generation
dtnsim.node[44].app.enable=true
dtnsim.node[44].app.bundlesNumber="5"
dtnsim.node[44].app.start="0"
dtnsim.node[44].app.destinationEid="1"
dtnsim.node[44].app.size="100"
dtnsim.node[45].app.enable=true
dtnsim.node[45].app.bundlesNumber="5"
dtnsim.node[45].app.start="0"
dtnsim.node[45].app.destinationEid="1"
dtnsim.node[45].app.size="100"
dtnsim.node[46].app.enable=true
dtnsim.node[46].app.bundlesNumber="5"
dtnsim.node[46].app.start="0"
dtnsim.node[46].app.destinationEid="1"
dtnsim.node[46].app.size="100"
dtnsim.node[47].app.enable=true
dtnsim.node[47].app.bundlesNumber="5"
dtnsim.node[47].app.start="0"
dtnsim.node[47].app.destinationEid="1"
dtnsim.node[47].app.size="100"
dtnsim.node[48].app.enable=true
dtnsim.node[48].app.bundlesNumber="5"
dtnsim.node[48].app.start="0"
dtnsim.node[48].app.destinationEid="1"
dtnsim.node[48].app.size="100"
dtnsim.node[49].app.enable=true
dtnsim.node[49].app.bundlesNumber="5"
dtnsim.node[49].app.start="0"
dtnsim.node[49].app.destinationEid="1"
dtnsim.node[49].app.size="100"
dtnsim.node[50].app.enable=true
dtnsim.node[50].app.bundlesNumber="5"
dtnsim.node[50].app.start="0"
dtnsim.node[50].app.destinationEid="1"
dtnsim.node[50].app.size="100"
dtnsim.node[51].app.enable=true
dtnsim.node[51].app.bundlesNumber="5"
dtnsim.node[51].app.start="0"
dtnsim.node[51].app.destinationEid="1"
dtnsim.node[51].app.size="100"
dtnsim.node[52].app.enable=true
dtnsim.node[52].app.bundlesNumber="5"
dtnsim.node[52].app.start="0"
dtnsim.node[52].app.destinationEid="1"
dtnsim.node[52].app.size="100"
dtnsim.node[53].app.enable=true
dtnsim.node[53].app.bundlesNumber="5"
dtnsim.node[53].app.start="0"
dtnsim.node[53].app.destinationEid="1"
dtnsim.node[53].app.size="100"
dtnsim.node[54].app.enable=true
dtnsim.node[54].app.bundlesNumber="5"
dtnsim.node[54].app.start="0"
dtnsim.node[54].app.destinationEid="1"
dtnsim.node[54].app.size="100"
dtnsim.node[55].app.enable=true
dtnsim.node[55].app.bundlesNumber="5"
dtnsim.node[55].app.start="0"
dtnsim.node[55].app.destinationEid="1"
dtnsim.node[55].app.size="100"
dtnsim.node[56].app.enable=true
dtnsim.node[56].app.bundlesNumber="5"
dtnsim.node[56].app.start="0"
dtnsim.node[56].app.destinationEid="1"
dtnsim.node[56].app.size="100"
dtnsim.node[57].app.enable=true
dtnsim.node[57].app.bundlesNumber="5"
dtnsim.node[57].app.start="0"
dtnsim.node[57].app.destinationEid="1"
dtnsim.node[57].app.size="100"
dtnsim.node[58].app.enable=true
dtnsim.node[58].app.bundlesNumber="5"
dtnsim.node[58].app.start="0"
dtnsim.node[58].app.destinationEid="1"
dtnsim.node[58].app.size="100"
dtnsim.node[59].app.enable=true
dtnsim.node[59].app.bundlesNumber="5"
dtnsim.node[59].app.start="0"
dtnsim.node[59].app.destinationEid="1"
dtnsim.node[59].app.size="100"
dtnsim.node[60].app.enable=true
dtnsim.node[60].app.bundlesNumber="5"
dtnsim.node[60].app.start="0"
dtnsim.node[60].app.destinationEid="1"
dtnsim.node[60].app.size="100"
dtnsim.node[61].app.enable=true
dtnsim.node[61].app.bundlesNumber="5"
dtnsim.node[61].app.start="0"
dtnsim.node[61].app.destinationEid="1"
dtnsim.node[61].app.size="100"
dtnsim.node[62].app.enable=true
dtnsim.node[62].app.bundlesNumber="5"
dtnsim.node[62].app.start="0"
dtnsim.node[62].app.destinationEid="1"
dtnsim.node[62].app.size="100"
dtnsim.node[63].app.enable=true
dtnsim.node[63].app.bundlesNumber="5"
dtnsim.node[63].app.start="0"
dtnsim.node[63].app.destinationEid="1"
dtnsim.node[63].app.size="100"
dtnsim.node[64].app.enable=true
dtnsim.node[64].app.bundlesNumber="5"
dtnsim.node[64].app.start="0"
dtnsim.node[64].app.destinationEid="1"
dtnsim.node[64].app.size="100"
dtnsim.node[65].app.enable=true
dtnsim.node[65].app.bundlesNumber="5"
dtnsim.node[65].app.start="0"
dtnsim.node[65].app.destinationEid="1"
dtnsim.node[65].app.size="100"
dtnsim.node[66].app.enable=true
dtnsim.node[66].app.bundlesNumber="5"
dtnsim.node[66].app.start="0"
dtnsim.node[66].app.destinationEid="1"
dtnsim.node[66].app.size="100"
dtnsim.node[67].app.enable=true
dtnsim.node[67].app.bundlesNumber="5"
dtnsim.node[67].app.start="0"
dtnsim.node[67].app.destinationEid="1"
dtnsim.node[67].app.size="100"
dtnsim.node[68].app.enable=true
dtnsim.node[68].app.bundlesNumber="5"
dtnsim.node[68].app.start="0"
dtnsim.node[68].app.destinationEid="1"
dtnsim.node[68].app.size="100"
dtnsim.node[69].app.enable=true
dtnsim.node[69].app.bundlesNumber="5"
dtnsim.node[69].app.start="0"
dtnsim.node[69].app.destinationEid="1"
dtnsim.node[69].app.size="100"
dtnsim.node[70].app.enable=true
dtnsim.node[70].app.bundlesNumber="5"
dtnsim.node[70].app.start="0"
dtnsim.node[70].app.destinationEid="1"
dtnsim.node[70].app.size="100"
dtnsim.node[71].app.enable=true
dtnsim.node[71].app.bundlesNumber="5"
dtnsim.node[71].app.start="0"
dtnsim.node[71].app.destinationEid="1"
dtnsim.node[71].app.size="100"
dtnsim.node[72].app.enable=true
dtnsim.node[72].app.bundlesNumber="5"
dtnsim.node[72].app.start="0"
dtnsim.node[72].app.destinationEid="1"
dtnsim.node[72].app.size="100"
dtnsim.node[73].app.enable=true
dtnsim.node[73].app.bundlesNumber="5"
dtnsim.node[73].app.start="0"
dtnsim.node[73].app.destinationEid="1"
dtnsim.node[73].app.size="100"
dtnsim.node[74].app.enable=true
dtnsim.node[74].app.bundlesNumber="5"
dtnsim.node[74].app.start="0"
dtnsim.node[74].app.destinationEid="1"
dtnsim.node[74].app.size="100"
dtnsim.node[75].app.enable=true
dtnsim.node[75].app.bundlesNumber="5"
dtnsim.node[75].app.start="0"
dtnsim.node[75].app.destinationEid="1"
dtnsim.node[75].app.size="100"
dtnsim.node[76].app.enable=true
dtnsim.node[76].app.bundlesNumber="5"
dtnsim.node[76].app.start="0"
dtnsim.node[76].app.destinationEid="1"
dtnsim.node[76].app.size="100"
#dtnsim.node[3].dtn.sdrSize = 9

# Nodes's failure rates
dtnsim.node[*].fault.faultSeed = ${repetition}*10
dtnsim.node[*].fault.meanTTF = ${TTF=0.1h,0.2h,0.5h,1h,2h,5h,10h,15h,20h,25h,30h,35h,40h}
dtnsim.node[*].fault.meanTTR = ${TTR=5h, 25h}

dtnsim.node[2].fault.enable = true
dtnsim.node[4].fault.enable = true
dtnsim.node[6].fault.enable = true
dtnsim.node[8].fault.enable = true
dtnsim.node[10].fault.enable = true
dtnsim.node[12].fault.enable = true
dtnsim.node[14].fault.enable = true
dtnsim.node[16].fault.enable = true
dtnsim.node[18].fault.enable = true
dtnsim.node[20].fault.enable = true
dtnsim.node[22].fault.enable = true
dtnsim.node[24].fault.enable = true
dtnsim.node[26].fault.enable = true
dtnsim.node[28].fault.enable = true
dtnsim.node[30].fault.enable = true
dtnsim.node[32].fault.enable = true
dtnsim.node[34].fault.enable = true
dtnsim.node[36].fault.enable = true
dtnsim.node[38].fault.enable = true
dtnsim.node[40].fault.enable = true
dtnsim.node[42].fault.enable = true
