[General]
allow-object-stealing-on-deletion = true
network = src.dtnsim
repeat = 100
sim-time-limit = 604801s
outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"
outputscalarmanager-class="omnetpp::envir::SqliteOutputScalarManager"
**.vector-recording=false
result-dir = results
dtnsim.nodesNumber = 109
dtnsim.node[*].dtn.routing = "cgrModelRev17Distribution"
dtnsim.node[*].dtn.numHags = 5
dtnsim.node[*].dtn.MeanTTF = "0.25_0.65_1.05_1.45_1.85"
dtnsim.node[*].dtn.MeanTTR = "25_25_25_25_25"
dtnsim.node[*].dtn.routingType = "routeListType:allPaths-firstDepleted,volumeAware:allContacts,extensionBlock:on,contactPlan:global,distribution:opportunistic,sdrModel:perNode"
#dtnsim.node[*].dtn.printRoutingDebug=true

dtnsim.central.contactsFile = "../FilteredContactPlans/contact_plan_7d_node-ids_5LEO_5HAP_5GS_TTR_25_25_25_25_25_TTF_0.25_0.65_1.05_1.45_1.85_opportunistic.txt"
dtnsim.node[44].app.enable=true
dtnsim.node[44].app.bundlesNumber="1000"
dtnsim.node[44].app.start="0"
dtnsim.node[44].app.destinationEid="1"
dtnsim.node[44].app.size="100"

# Nodes's failure rates
dtnsim.node[2].fault.faultSeed = ${repetition}*100
dtnsim.node[2].fault.meanTTF = 0.25h
dtnsim.node[2].fault.meanTTR = 25h
dtnsim.node[4].fault.faultSeed = ${repetition}*100
dtnsim.node[4].fault.meanTTF = 0.65h
dtnsim.node[4].fault.meanTTR = 25h
dtnsim.node[6].fault.faultSeed = ${repetition}*100
dtnsim.node[6].fault.meanTTF = 1.05h
dtnsim.node[6].fault.meanTTR = 25h
dtnsim.node[8].fault.faultSeed = ${repetition}*100
dtnsim.node[8].fault.meanTTF = 1.45h
dtnsim.node[8].fault.meanTTR = 25h
dtnsim.node[10].fault.faultSeed = ${repetition}*100
dtnsim.node[10].fault.meanTTF = 1.85h
dtnsim.node[10].fault.meanTTR = 25h

dtnsim.node[2].fault.enable = true
dtnsim.node[4].fault.enable = true
dtnsim.node[6].fault.enable = true
dtnsim.node[8].fault.enable = true
dtnsim.node[10].fault.enable = true